CREATE DATABASE hiddenCost;
CREATE TABLE INGREDIENTES
(
	id_ingrediente INTEGER identity(1,1) PRIMARY KEY NOT NULL,
	preco DECIMAL(10,2),
	peso DECIMAL(10,2),
	nome VARCHAR(70) NOT NULL
)
CREATE TABLE USUARIOS
(
	id_usuario INTEGER identity(1,1) PRIMARY KEY NOT NULL,
	nome VARCHAR(50) NOT NULL,
	senha VARCHAR(30) NOT NULL,
	email VARCHAR(60) NOT NULL
)
CREATE TABLE PRODUTOS_VENDAS	
(
	id_produto INTEGER identity(1,1) PRIMARY KEY NOT NULL,
	id_usuario INTEGER NOT NULL,
	nome VARCHAR(30) NOT NULL,
	preco_unitario DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_produto_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIOS (id_usuario)
)
CREATE TABLE PRODUTOS_VENDAS_INGREDIENTES	
(
	id_produto_ingrediente INTEGER identity(1,1) PRIMARY KEY NOT NULL,
	id_produto INTEGER NOT NULL,
	id_ingrediente INTEGER NOT NULL,
	CONSTRAINT FK_produto_ingrediente FOREIGN KEY (id_produto) REFERENCES PRODUTOS_VENDAS (id_produto),
	CONSTRAINT FK_ingrediente FOREIGN KEY (id_ingrediente) REFERENCES INGREDIENTES (id_ingrediente)
)
CREATE TABLE PERFIS
(
	id_perfil INTEGER identity(1,1) PRIMARY KEY NOT NULL,
	id_usuario INTEGER NOT NULL,
	tipo VARCHAR(10) NOT NULL, -- ADMIN, COMUM
	CONSTRAINT FK_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
)
CREATE TABLE EQUIPAMENTOS
(
	id_equipamento INTEGER identity(1,1) PRIMARY KEY NOT NULL,
	tipo VARCHAR(20) NOT NULL, -- UTENSILIOS, ELETRODOMESTICO 
	quantidade INTEGER NOT NULL,
	marca VARCHAR(20) NOT NULL,
	cosumoWatt DECIMAL(10,2) NOT NULL
)
CREATE TABLE PRODUTOS_VENDAS_EQUIPAMENTOS	
(
	id_produto_equipamento INTEGER identity(1,1) PRIMARY KEY NOT NULL,
	id_produto INTEGER NOT NULL,
	id_equipamento INTEGER NOT NULL,
	CONSTRAINT FK_produto_equipamento FOREIGN KEY (id_produto) REFERENCES PRODUTOS_VENDAS (id_produto),
	CONSTRAINT FK_equipamento FOREIGN KEY (id_equipamento) REFERENCES EQUIPAMENTOS (id_equipamento)
)

Insert into USUARIOS (nome, email, senha) values ('Dayane Damaceno', 'dayane.damaceno@hotmail.com', 'teste')

DROP TABLE PRODUTOS_VENDAS_EQUIPAMENTOS;
DROP TABLE EQUIPAMENTOS;
DROP TABLE PERFIS;
DROP TABLE USUARIOS;
DROP TABLE PRODUTOS_VENDAS_INGREDIENTES;
DROP TABLE PRODUTOS_VENDAS;
DROP TABLE INGREDIENTES;